#!/bin/bash

#change both the vivado_path and the project name to yours if required.
vivado_path=/tools/Xilinx/Vivado/2018.3/bin
project_name=xc7z010_hyperion

cd ../

$vivado_path/vivado -source ./rebuild/$project_name.tcl